# Generated by Django 4.2.7 on 2025-10-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredientcategory_ingredientitem_recipeingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='food_type',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('side_dish', 'Side Dish'), ('soup', 'Soup'), ('salad', 'Salad'), ('beverage', 'Beverage'), ('snack', 'Snack'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('other', 'Other')], default='main_course', max_length=20),
        ),
    ]
