# Generated by Django 4.2.7 on 2025-10-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('american', 'American'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('thai', 'Thai'), ('indian', 'Indian'), ('french', 'French'), ('greek', 'Greek'), ('spanish', 'Spanish'), ('middle_eastern', 'Middle Eastern'), ('korean', 'Korean'), ('vietnamese', 'Vietnamese'), ('mediterranean', 'Mediterranean'), ('caribbean', 'Caribbean'), ('african', 'African'), ('other', 'Other')], help_text='Cuisine type of the recipe', max_length=30, null=True),
        ),
    ]
